# Generated by Django 4.2.7 on 2024-02-02 13:26

from django.db import migrations

def add_machines(apps, schema_editor):
    Machine = apps.get_model('machines', 'Machine')
    titles = (
        *[f"CM{i:02}" for i in range(1, 31)],  # CM01 - CM30
        *[f"UM{i:02}" for i in range(1, 13)],  # UM01 - UM12
        *[f"UT{i:02}" for i in range(1, 13)],  # UT01 - UT12
        *[f"CT{i:02}" for i in range(1, 9)],   # CT01 - CT08
        *[f"WI{i:02}" for i in range(1, 9)],   # WI01 - WI08
        *[f"WE{i:02}" for i in range(1, 6)],   # WE01 - WE05
        *[f"S{i:02}" for i in range(1, 6)],    # S01 - S05
    )
    for title in titles:
        Machine.objects.create(title=title)

class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_machines),
    ]
