# Generated by Django 4.2.7 on 2024-04-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_seed_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='sort_order',
            field=models.PositiveIntegerField(default=1, verbose_name='Sort Order'),
        ),
    ]
