# Generated by Django 4.2.7 on 2023-12-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_part_options_alter_part_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
