# Generated by Django 4.2.7 on 2024-04-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_part_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='sort_order',
            field=models.PositiveIntegerField(default=1, verbose_name='Sort Order'),
        ),
    ]
