# Generated by Django 4.2.7 on 2024-04-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_client_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sort_order',
            field=models.PositiveIntegerField(default=1, verbose_name='Sort Order'),
        ),
    ]
