# Generated by Django 4.2.7 on 2023-12-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=200, null=True, verbose_name='Phone Number'),
        ),
    ]
