# Generated by Django 4.2.7 on 2023-12-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='title',
        ),
    ]
