# Generated by Django 4.2.7 on 2023-12-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_rename_name_client_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
