# Generated by Django 4.2.7 on 2024-01-05 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('started_at', models.TimeField(verbose_name='Started At')),
                ('ended_at', models.TimeField(null=True, verbose_name='Ended At')),
                ('standard_time', models.IntegerField(verbose_name='Standard Time')),
                ('intact_parts_count', models.IntegerField(verbose_name='Intact Parts Count')),
                ('defective_parts_count', models.IntegerField(verbose_name='Defective Parts Count')),
                ('status', models.CharField(choices=[('p', 'Pending'), ('a', 'Approved'), ('r', 'Rejected')], default='p', max_length=20, verbose_name='Status')),
                ('stop_controller_1_code', models.CharField(blank=True, max_length=10, null=True)),
                ('stop_controller_1_time', models.IntegerField(blank=True, null=True)),
                ('stop_controller_2_code', models.CharField(blank=True, max_length=10, null=True)),
                ('stop_controller_2_time', models.IntegerField(blank=True, null=True)),
                ('stop_controller_3_code', models.CharField(blank=True, max_length=10, null=True)),
                ('stop_controller_3_time', models.IntegerField(blank=True, null=True)),
                ('stop_controller_4_code', models.CharField(blank=True, max_length=10, null=True)),
                ('stop_controller_4_time', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine', verbose_name='Machine')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
