# Generated by Django 4.2.7 on 2023-11-17 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stages', '0002_alter_stage_options_alter_stage_title'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterField(
            model_name='report',
            name='defective_parts_count',
            field=models.IntegerField(verbose_name='Defective Parts Count'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ended_at',
            field=models.DateTimeField(verbose_name='Ended At'),
        ),
        migrations.AlterField(
            model_name='report',
            name='intact_parts_count',
            field=models.IntegerField(verbose_name='Intact Parts Count'),
        ),
        migrations.AlterField(
            model_name='report',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stage', verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='report',
            name='standard_time',
            field=models.DateTimeField(verbose_name='Standard Time'),
        ),
        migrations.AlterField(
            model_name='report',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started At'),
        ),
        migrations.AlterField(
            model_name='report',
            name='stop_time',
            field=models.IntegerField(verbose_name='Stop Time'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
