# Generated by Django 4.2.7 on 2024-01-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='a', max_length=20, verbose_name='Category'),
        ),
    ]
