# Generated by Django 4.2.7 on 2023-11-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
        ),
    ]
