# Generated by Django 4.2.7 on 2024-01-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='category',
        ),
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
    ]
