# Generated by Django 4.2.7 on 2024-04-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_category_remove_report_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sort_order',
            field=models.PositiveIntegerField(default=1, verbose_name='Sort Order'),
        ),
    ]
