# Generated by Django 4.2.7 on 2023-12-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_created_at_order_started_at'),
        ('reports', '0005_report_stop_controller_1_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order'),
        ),
    ]
