# Generated by Django 4.2.7 on 2024-04-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_parts_report_parts_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='report',
            name='parts_code',
        ),
    ]
