# Generated by Django 4.2.7 on 2023-12-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_user'),
        ('reports', '0006_report_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(max_length=20, choices=[('p', 'Pending'), ('a', 'Approved'), ('r', 'Rejected')], default='p', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client'),
        ),
    ]
