# Generated by Django 4.2.7 on 2023-12-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_status_alter_report_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user',
            new_name='client',
        ),
    ]
