# Generated by Django 4.2.7 on 2024-04-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_part_sort_order'),
        ('reports', '0007_remove_report_parts_remove_report_parts_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='parts',
            field=models.ManyToManyField(to='parts.part', verbose_name='Parts'),
        ),
        migrations.AddField(
            model_name='report',
            name='parts_code',
            field=models.JSONField(default=list, verbose_name='Parts Code'),
        ),
    ]
