# Generated by Django 4.2.7 on 2024-04-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_parts_report_parts_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Parts_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Report Part Code',
                'verbose_name_plural': 'Report Part Code',
            },
        ),
    ]
