# Generated by Django 4.2.7 on 2023-12-06 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_rename_user_report_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='stage',
        ),
    ]
