# Generated by Django 4.2.7 on 2023-12-06 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        ('reports', '0009_remove_report_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='machines.machine', verbose_name='Machine'),
            preserve_default=False,
        ),
    ]
