# Generated by Django 4.2.7 on 2024-04-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_parts_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='parts_code',
        ),
        migrations.AddField(
            model_name='report_parts_code',
            name='Number',
            field=models.IntegerField(default=1, verbose_name='Number'),
        ),
        migrations.AddField(
            model_name='report_parts_code',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.report', verbose_name='Report'),
        ),
    ]
