# Generated by Django 4.2.7 on 2023-12-07 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_created_at_order_started_at'),
        ('reports', '0010_report_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order'),
        ),
    ]
