# Generated by Django 4.2.7 on 2024-04-12 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_remove_report_parts_code_report_parts_code_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_parts_code',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report', verbose_name='Report'),
        ),
    ]
