# Generated by Django 4.2.7 on 2024-04-12 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_report_parts_code_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_parts_code',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report_parts_code',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
