# Generated by Django 4.2.7 on 2024-04-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_report_parts_code_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_parts_code',
            old_name='Number',
            new_name='number',
        ),
    ]
