# Generated by Django 4.2.7 on 2024-04-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_rename_number_report_parts_code_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_parts_code',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='report_parts_code',
            name='updated_at',
        ),
    ]
