# Generated by Django 4.2.7 on 2024-04-12 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_part_sort_order'),
        ('reports', '0014_remove_report_parts_code_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='parts',
        ),
        migrations.AddField(
            model_name='report',
            name='parts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.part', verbose_name='Parts'),
            preserve_default=False,
        ),
    ]
