# Generated by Django 4.2.7 on 2024-04-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_part_sort_order'),
        ('reports', '0015_remove_report_parts_report_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='parts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.part', verbose_name='Parts'),
        ),
    ]
