# Generated by Django 4.2.7 on 2024-04-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_alter_report_parts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='parts',
            new_name='part',
        ),
    ]
