# Generated by Django 4.2.7 on 2023-12-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_alter_report_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='standard_time',
            field=models.IntegerField(verbose_name='Standard Time'),
        ),
    ]
