# Generated by Django 4.2.7 on 2023-12-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_alter_report_standard_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ended_at',
            field=models.DateField(null=True, verbose_name='Ended At'),
        ),
        migrations.AlterField(
            model_name='report',
            name='started_at',
            field=models.DateField(auto_now_add=True, verbose_name='Started At'),
        ),
    ]
