# Generated by Django 4.2.7 on 2023-12-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_alter_report_ended_at_alter_report_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='started_at',
            field=models.DateField(verbose_name='Started At'),
        ),
    ]
