# Generated by Django 4.2.7 on 2023-12-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_auto_20231217_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ended_at',
            field=models.TimeField(null=True, verbose_name='Ended At'),
        ),
        migrations.AlterField(
            model_name='report',
            name='started_at',
            field=models.TimeField(verbose_name='Started At'),
        ),
    ]
