# Generated by Django 4.2.7 on 2023-11-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'مرحله', 'verbose_name_plural': 'مرحله'},
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
