# Generated by Django 4.2.7 on 2024-01-05 20:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('parts', '0003_part_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('started_at', models.DateField(default=django.utils.timezone.now, verbose_name='Started At')),
                ('ended_at', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Ended At')),
                ('order_number', models.CharField(max_length=200, verbose_name='Order Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part', verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
