# Generated by Django 4.2.7 on 2023-11-17 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_part_options_alter_part_created_at_and_more'),
        ('clients', '0002_alter_client_options_alter_client_email_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 14, 28, 28, 257522), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=200, verbose_name='Order Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='parts',
            field=models.ManyToManyField(to='parts.part', verbose_name='Parts'),
        ),
    ]
