# Generated by Django 4.2.7 on 2023-11-17 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_order_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 15, 13, 11, 323259), verbose_name='Created At'),
        ),
    ]
