# Generated by Django 4.2.7 on 2023-11-17 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 15, 47, 45, 115617), verbose_name='Created At'),
        ),
    ]
