# Generated by Django 4.2.7 on 2023-11-27 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='started_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Started At'),
        ),
    ]
