# Generated by Django 4.2.7 on 2023-12-11 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ended_at',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Ended At'),
        ),
    ]
