# Generated by Django 4.2.7 on 2023-12-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_part_options_alter_part_created_at_and_more'),
        ('orders', '0011_alter_order_ended_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='parts',
        ),
        migrations.AddField(
            model_name='order',
            name='parts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.part', verbose_name='Part'),
        ),
    ]
