# Generated by Django 4.2.7 on 2023-12-11 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_part_options_alter_part_created_at_and_more'),
        ('orders', '0012_remove_order_parts_order_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='parts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part', verbose_name='Part'),
        ),
    ]
