# Generated by Django 4.2.7 on 2023-12-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_parts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='parts',
            new_name='part',
        ),
    ]
